name: Playwright Tests
on:
  push:
    branches: [main]
jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --shard=${{ matrix.shard }}/3
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: blob-report-${{ matrix.shard}}
          path: blob-report 
      - name: Upload Monocart Report
        uses: actions/upload-artifact@v4
        with:
          name: monocart-report-${{ matrix.shard}}
          path: monocart-report
    continue-on-error: true        
            

  merge-reports:
    needs: [playwright-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name : Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true
      - name: Merge Playwright Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports
      - name: Upload Merged Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: playwright-report
          retention-days: 30
      - name : Download Monocart Report
        uses: actions/download-artifact@v4
        with:
          path: monocart-report-1
          pattern: index.json
          merge-multiple: true
      - name : Download Monocart Report
        uses: actions/download-artifact@v4
        with:
          path: monocart-report-2
          pattern: index.json
          merge-multiple: true
      - name : Download Monocart Report
        uses: actions/download-artifact@v4
        with:
          path: monocart-report-3
          pattern: index.json
          merge-multiple: true
      - name: Merge Playwright Report
        run: node merge.mjs
      - name: Upload Merged Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: monocart-report
          path: monocart-report
          retention-days: 30                
         

       
